# Generated by Django 3.2.18 on 2023-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sensors',
            field=models.ManyToManyField(to='core.Sensor'),
        ),
    ]
