# Generated by Django 3.2.18 on 2023-03-19 22:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.device_image_file_path),
        ),
    ]
